export const authConstants = {
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',
	LOGOUT_REQUEST: 'LOGOUT_REQUEST',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

export const userConstants = {
	USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
	USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
	USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
}

export const productConstants = {

    GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",
    CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
    CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
    CREATE_PRODUCT_FAILURE: "CREATE_PRODUCT_FAILURE",
};
